import LayoutClient from '@/components/layout/Layout'
import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import { AuthProvider } from '@/context/AuthContext'
import { NextUIProvider } from '@nextui-org/react'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: '/logo.svg'
}

export const viewport: Viewport = {
	themeColor: 'black',
	colorScheme: 'dark'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<NextUIProvider>
					<AuthProvider>
						<LayoutClient>{children}</LayoutClient>
					</AuthProvider>
				</NextUIProvider>
			</body>
		</html>
	)
}
